name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  
 
jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to

    steps:
    # pobranie repozytorium
    - uses: actions/checkout@v3

    # instalacja .NET
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x
        
    # pobranie paczek NuGet do naszego projektu
    - name: Restore dependecies
      run: dotnet restore
      
    # budowanie projektu
    - name: Build
      run: dotnet build --no-restore
      
    # przeprowadzenie testów
    - name: Test
      run: dotnet test
